/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginStudentRouteImport } from './routes/login.student'
import { Route as LoginDriverRouteImport } from './routes/login.driver'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginStudentRoute = LoginStudentRouteImport.update({
  id: '/login/student',
  path: '/login/student',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginDriverRoute = LoginDriverRouteImport.update({
  id: '/login/driver',
  path: '/login/driver',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/driver': typeof DriverRoute
  '/student': typeof StudentRoute
  '/login/driver': typeof LoginDriverRoute
  '/login/student': typeof LoginStudentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/driver': typeof DriverRoute
  '/student': typeof StudentRoute
  '/login/driver': typeof LoginDriverRoute
  '/login/student': typeof LoginStudentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/driver': typeof DriverRoute
  '/student': typeof StudentRoute
  '/login/driver': typeof LoginDriverRoute
  '/login/student': typeof LoginStudentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/driver'
    | '/student'
    | '/login/driver'
    | '/login/student'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/driver'
    | '/student'
    | '/login/driver'
    | '/login/student'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/driver'
    | '/student'
    | '/login/driver'
    | '/login/student'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DriverRoute: typeof DriverRoute
  StudentRoute: typeof StudentRoute
  LoginDriverRoute: typeof LoginDriverRoute
  LoginStudentRoute: typeof LoginStudentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/student': {
      id: '/login/student'
      path: '/login/student'
      fullPath: '/login/student'
      preLoaderRoute: typeof LoginStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/driver': {
      id: '/login/driver'
      path: '/login/driver'
      fullPath: '/login/driver'
      preLoaderRoute: typeof LoginDriverRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DriverRoute: DriverRoute,
  StudentRoute: StudentRoute,
  LoginDriverRoute: LoginDriverRoute,
  LoginStudentRoute: LoginStudentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
